---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ols-load-generator-serviceaccount
  namespace: ols-load-generator
rules:
- apiGroups: ["extensions", "apps", "batch", "security.openshift.io", "policy"]
  resources: ["deployments", "jobs", "pods", "services", "jobs/status", "podsecuritypolicies", "securitycontextconstraints"]
  verbs: ["use", "get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ols-load-generator-role
  namespace: ols-load-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ols-load-generator-serviceaccount
subjects:
- kind: ServiceAccount
  name: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ols-load-generator-orchestrator
  namespace: ols-load-generator
  labels:
    ols-load-generator-component: orchestrator
spec:
  template:
    spec:
      containers:
      - name: ols-load-generatoring
        image: quay.io/vchalla/ols-load-generator:amd64
        securityContext:
          privileged: true
        env:
          - name: OLS_TEST_HOST
            value: <ols-host-url>
          - name: OLS_TEST_UUID
            value: <ols-test-uuid>
          - name: OLS_TEST_AUTH_TOKEN
            value: <ols-auth-token>
          - name: OLS_TEST_DURATION
            value: <your-test-duration>
          - name: OLS_TEST_WORKERS
            value: <parallel-test-workers>
          - name: OLS_TEST_METRIC_STEP
            value: <your-step-size>
          - name: OLS_TEST_PROFILES
            value: <comma-separared-yamls>
          - name: OLS_TEST_ES_HOST
            value: <es-url>
          - name: OLS_TEST_ES_INDEX
            value: <es-index>
        volumeMounts:
          - name: kubeconfig-volume
            mountPath: /etc/kubeconfig
            readOnly: true
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
        imagePullPolicy: Always
      restartPolicy: Never
      volumes:
        - name: kubeconfig-volume
          secret:
            secretName: kubeconfig-secret
  backoffLimit: 0