---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ols-load-generator-serviceaccount
  namespace: ols-load-generator
rules:
- apiGroups: ["extensions", "apps", "batch", "security.openshift.io", "policy"]
  resources: ["deployments", "jobs", "pods", "services", "jobs/status", "podsecuritypolicies", "securitycontextconstraints"]
  verbs: ["use", "get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ols-load-generator-role
  namespace: ols-load-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ols-load-generator-serviceaccount
subjects:
- kind: ServiceAccount
  name: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ols-load-generator-orchestrator
  namespace: ols-load-generator
  labels:
    ols-load-generator-component: orchestrator
spec:
  template:
    spec:
      containers:
      - name: ols-load-generatoring
        image: quay.io/vchalla/ols-load-generator:amd64
        securityContext:
          privileged: true
        env:
          - name: OLS_TEST_HOST
            value: <ols-host-url>
          - name: OLS_TEST_RUNID
            value: <ols-test-runid>
          - name: OLS_TEST_AUTH_TOKEN
            value: <ols-auth-token>
          - name: OLS_TEST_HIT_SIZE
            value: <hit-size>
          - name: OLS_TEST_RPS
            value: <requests-per-second>
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0